//Chatgpt made the code for exporting and importing a long list of things,
// I did not want to have the list part of the mainmenu.js, cause it would take up
// too much space and clutter the script more.

// I got all the images from the original game and stacked them in a github repository
const background_Image_Names = [
    "alex_gem_our_small_fleet.jpg",
    "battleghost_alyx.png",
    "betel_arg_welcome_to_gmod.jpg",
    "brezz_prop_wars.jpg",
    "busti_crazy_builders.jpg",
    "candyapple_kleiner_and_lamarr.jpg",
    "chernobill_gary_mod.jpg",
    "cobalt_tables_have_turned.jpg",
    "con_citizens_revolt.png",
    "cptsledgehammer_gmod_chapel.jpg",
    "dipski_garrys_express.png",
    "dirtypeso_a_world_of_pure_imagination.png",
    "du_citadel_core_meltdown.jpg",
    "edd_construct_isometric.png",
    "filmchae_making_way.jpg",
    "gizmo_the_canbine.jpg",
    "glassesman_metrocop_in_tunnel.jpg",
    "hauptmann_cone_thief.jpg",
    "hiddenwave8d_noshpa_gmod_workshop.png",
    "hydralisk_fire.png",
    "idiotdoug_bucket_by_the_window.png",
    "idiotdoug_red_and_blue.png",
    "ink_railroad.jpg",
    "intruso_orangebox_race.jpg",
    "ivretor_super_valve_bros.png",
    "kushpew_i_want_that_physgun.jpg",
    "kushpew_mom_help.jpg",
    "lemon_juice_dome_land.jpg",
    "lukaswbrr_one_new_universe.png",
    "lunascribbles_poker_in_space.png",
    "madsonium_welcome_to_gmod.jpg",
    "minic23_discover.png",
    "noga_gm.jpg",
    "noga_meeting_in_the_ruins.jpg",
    "noga_the_first_snow.png",
    "noshpa_pick_up_that_can.jpg",
    "olmate_ubafest_kowloon_sky_city.jpg",
    "olmate_ubafest_shrine_of_the_physgod.jpg",
    "operator7191_gravity.jpg",
    "pajtajster_gwick.jpg",
    "paz_3_star_check_in.jpg",
    "paz_prop_hunt_alyx.jpg",
    "piggo_flight_of_the_construct.jpg",
    "ribbit_stools_and_drinks.png",
    "sekai_memories.png",
    "shikardos007_under_the_bridge.png",
    "shut_up_bofreemian_rhapsody.jpg",
    "teops_g_planet.png",
    "thenebeskymuz_city_seventeen.png",
    "underain_midway.jpg",
    "xenonuke_gateway_station.png"
];
export default background_Image_Names;